### ISSUE TITLE
没有意义的项目

### ISSUE THREAD

**Issue by jasonfish568** [chenlinzhong/php-delayqueue#1]
1. 重复造轮子，建议学习下现代PHP框架的特性
2. 项目结构太过原始，建议现代框架如何通过composer引入package
3. 没有封装好可变参数
4. 没有足够的注释

**Comment by fankux** [comment]
（利益相关：该项目深度参与者）该项目是作者工作之余写的，设立的思路是按照业务系统来的，然后在组里推广一段时间，很好的解决了很多消息定时发送的业务场景（例如微博私信定时提醒），把很多业务都存在的重复逻辑抽离成了独立系统，直接服务于业务，让业务专注于业务。我持续和作者构思设计思路，近期正在高优做的就是，从“业务系统风格”往“专业”的“通用化组件”风格重构。您提到的问题都有涉及。

1.关于“重复造轮子”这个经典话题。对于生产环境，开源框架和系统缺如果乏有力的人员和技术支持，是不推荐使用的，一旦故障无法及时止损和定位，黑盒就像一个定时炸弹。由于公司运维团队能力有限，宁可做一个尽管比较糙，但是自己能够控制住“前后左右”的轮子。
2.很好的建议，确实需要改造这块。
3.是指接口？目前接口正在重构。
4.目前架构比较简单，关键点会加注释。

**Comment by wi1dcard** [comment]
确实，例如 Laravel 也有类似的 `Event` / `Queue` 实现，感觉这个开源出来依旧停留在只能「学习原理」的阶段上，缺乏规范和文档。当然，在公司内部推广还是很不错的，感觉如果作者真的想要做成不错的开源项目，还需要进行大量地完善。

**Comment by ycqqq** [comment]
看源码前先给个星星，作者是哪个公司的？

**Comment by venusaulis** [comment]
star支持，希望继续更新。包容不同的声音。例如larveral确实做得不错，但不代表yii，tp，ci就是重复造轮子了。我相信总会有各自发挥优势的场合。

**Comment by bapijun** [comment]
自己制造轮子,起码可以再学习网络的知识,我也是在准备自己写一个延时队列的时候看到楼主这个链接的,可以打算借鉴楼主的时候,.准备用redis的另一套机制来实现

**Comment by Yaoxj** [comment]
有空学习一下，不过这个如果取出任务没执行 crash了 是不是还是要借助扫表去排查没有消费成功的延时任务呢

**Comment by longit123** [comment]
laravel吹的真的是呵呵了...

一个照搬java在N年前就普及的设计模式，鼓吹多么多么牛逼....

一个服务启动后，加载十几个甚至几十个类实例，ORM臃肿不堪，慢的一比（几乎没什么优化空间，呵呵）；

一个默认依赖几十个黑盒vendor的框架，出点问题急不死你的框架；

一堆只会CRUD，看了几篇laravel自我吹嘘洗脑文章，流着哈喇子，瞬间变成脑残粉的搬砖民工们，叫嚣着：你们做的东西laravel都有，你们做的都是无意义的东西（对，说的就是你，是不是不服不忿的？哈哈，气大伤身）；

送它们一句话吧：好好搬砖（35岁后，送外卖是你们的归宿）。

作者别管别人说什么，自己加油（是不是重复造轮子管你们毛事？）

**Comment by jasonfish568** [comment]
我觉得longit123你可能需要先好好学习下英语，然后看看国外的世界是什么样的。

之所以我在这里会说这个项目没有意义，是因为这个repo是在某公号上作为样本进行了推崇的，如果当时这个公号确实引导了新手程序员向这个架构的项目看齐的话，我觉得真是坑的很彻底。我在这个issue里说得问题是要被公号引流来的新手程序员，注意到响应的问题，不要走歪路，提升社区质量。

longit123我觉得如果你对Laravel有什么误解，或者对开源MVC框架有什么仇恨的话，请你去相应的Repo下喷，看看会有多少人过来怼你。

每个语言每个框架都有自己的优缺点，现代MVC框架走到今天不是你一句依赖黑盒就讽刺的了得。真不知道你在用开源资源的时候是以什么心态来面对的。我用Laravel做项目，完整支撑了两个千万级流水的项目，你觉得是只是CRUD能完成的吗？我们非常理解什么叫无知者无畏，所以也知道你这种人是无药可救的。就好像当初那些嘲讽着PHP的人却连PHP的代码都写不出一行一样。

简单说，Github不是你这种人活动的区域。请轱辘着离开这里

**Comment by yesiscoach** [comment]
适合自己用才是最好的，其他的都是第二

**Comment by fankux** [comment]
希望大家就事论事，以技术讨论的角度交流，不要上升到人身和地位攻击。
